#!/usr/bin/env python3
"""
Daily Digest — Generates a prioritized daily job search report.
Scans all sources, scores jobs with resume matcher, emails summary.
"""

import json
import smtplib
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent
load_dotenv(BASE_DIR / ".env")

def load_json(path):
    p = BASE_DIR / path
    if p.exists():
        with open(p) as f:
            return json.load(f)
    return []

def send_digest(to_email, subject, body):
    """Send digest email via Gmail."""
    from_addr = "AbdullahFageeh@gmail.com"
    password = "cucfcehiapgxttyh"
    
    msg = MIMEMultipart()
    msg["From"] = from_addr
    msg["To"] = to_email
    msg["Subject"] = f"[Daily Job Digest] {subject}"
    msg.attach(MIMEText(body, "html"))
    
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(from_addr, password)
        server.send_message(msg)
        server.quit()
        print("✅ Digest email sent!")
    except Exception as e:
        print(f"❌ Email failed: {e}")

def generate_digest():
    """Generate daily digest of new jobs."""
    entry_jobs = load_json("logs/entry_level_jobs.json")
    other_jobs = load_json("logs/other_jobs.json")
    linkedin_applied = load_json("logs/linkedin_applied.json")
    
    today = datetime.now().strftime("%Y-%m-%d")
    today_entry = [j for j in entry_jobs if j.get("found_at", "").startswith(today)]
    today_other = [j for j in other_jobs if j.get("found_at", "").startswith(today)]
    applied_today = [a for a in linkedin_applied if a.get("date", "").startswith(today)]
    
    body = f"""
    <h2>📋 Daily Job Search Digest — {today}</h2>
    
    <h3>🎯 New Entry-Level Jobs Found: {len(today_entry)}</h3>
    <table border="1" cellpadding="5" cellspacing="0">
    <tr><th>Role</th><th>Company</th><th>Link</th></tr>
    """
    
    for j in today_entry[:15]:
        body += f'<tr><td>{j.get("title","")}</td><td>{j.get("company","")}</td><td><a href="{j["link"]}">Apply</a></td></tr>\n'
    
    body += f"""
    </table>
    
    <h3>📧 Applications Today: {len(applied_today)}</h3>
    <table border="1" cellpadding="5" cellspacing="0">
    <tr><th>Role</th><th>Company</th><th>Method</th></tr>
    """
    
    for a in applied_today:
        body += f'<tr><td>{a.get("title","")}</td><td>{a.get("company","")}</td><td>{a.get("method","manual")}</td></tr>\n'
    
    body += """
    </table>
    <hr>
    <p><i>Auto-generated by Job Search Automation</i></p>
    """
    
    send_digest(
        "AbdullahFageeh@gmail.com",
        f"{len(today_entry)} New Entry-Level Ops Jobs",
        body
    )
    
    # Also save to file
    digest_path = BASE_DIR / "logs" / f"digest_{today}.html"
    digest_path.write_text(body, encoding="utf-8")
    print(f"💾 Digest saved to {digest_path}")

if __name__ == "__main__":
    generate_digest()