#!/usr/bin/env python3
"""
Daily Digest — Generates a prioritized daily job search report.
Scans all sources, scores jobs with resume matcher, emails summary.
"""

import json
import os
import smtplib
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent
load_dotenv(BASE_DIR / ".env")

def load_json(path):
    p = BASE_DIR / path
    if p.exists():
        with open(p) as f:
            return json.load(f)
    return []

def send_digest(to_email, subject, body):
    """Send digest email via Gmail."""
    from_addr = "AbdullahFageeh@gmail.com"
    password = os.getenv("GMAIL_APP_PASSWORD", "")
    if not password:
        print("Email skipped: GMAIL_APP_PASSWORD is not configured.")
        return
    
    msg = MIMEMultipart()
    msg["From"] = from_addr
    msg["To"] = to_email
    msg["Subject"] = f"[Daily Job Digest] {subject}"
    msg.attach(MIMEText(body, "html"))
    
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(from_addr, password)
        server.send_message(msg)
        server.quit()
        print("✅ Digest email sent!")
    except Exception as e:
        print(f"❌ Email failed: {e}")

def generate_digest():
    """Generate daily digest of new jobs (last 7 days)."""
    from datetime import datetime, timedelta
    
    entry_jobs = load_json("logs/entry_level_jobs.json")
    other_jobs = load_json("logs/other_jobs.json")
    linkedin_applied = load_json("logs/linkedin_applied.json")
    
    today = datetime.now().strftime("%Y-%m-%d")
    week_ago = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
    
    # Show jobs from last 7 days (not just today)
    recent_entry = [j for j in entry_jobs if j.get("found_at", "").startswith(week_ago) or j.get("found_at", "").startswith(today)]
    recent_other = [j for j in other_jobs if j.get("found_at", "").startswith(week_ago) or j.get("found_at", "").startswith(today)]
    
    # Also include all jobs if fewer than 10 found (first run scenario)
    if len(recent_entry) + len(recent_other) < 10:
        recent_entry = entry_jobs
        recent_other = other_jobs
    
    applied_today = [a for a in linkedin_applied if a.get("date", "").startswith(today)]
    
    body = f"""
    <h2>📋 Daily Job Search Digest — {today}</h2>
    <p><i>Showing jobs from the last 7 days</i></p>
    
    <h3>🎯 Entry-Level Jobs Found: {len(recent_entry)}</h3>
    <table border="1" cellpadding="5" cellspacing="0">
    <tr><th>Role</th><th>Company</th><th>Date</th><th>Link</th></tr>
    """
    
    for j in recent_entry[:20]:
        body += f'<tr><td>{j.get("title","")}</td><td>{j.get("company","")}</td><td>{j.get("found_at","")[:10]}</td><td><a href="{j.get("link","#")}">Apply</a></td></tr>\n'
    
    body += f"""
    </table>
    
    <h3>📋 Other Board Jobs Found: {len(recent_other)}</h3>
    <table border="1" cellpadding="5" cellspacing="0">
    <tr><th>Role</th><th>Source</th><th>Date</th><th>Link</th></tr>
    """
    
    for j in recent_other[:20]:
        body += f'<tr><td>{j.get("title","")}</td><td>{j.get("source","")}</td><td>{j.get("found_at","")[:10]}</td><td><a href="{j.get("link","#")}">Apply</a></td></tr>\n'
    
    body += f"""
    </table>
    
    <h3>📧 Applications Today: {len(applied_today)}</h3>
    <table border="1" cellpadding="5" cellspacing="0">
    <tr><th>Role</th><th>Company</th><th>Method</th></tr>
    """
    
    for a in applied_today:
        body += f'<tr><td>{a.get("title","")}</td><td>{a.get("company","")}</td><td>{a.get("method","manual")}</td></tr>\n'
    
    body += """
    </table>
    <hr>
    <p><i>Auto-generated by Job Search Automation</i></p>
    """
    
    send_digest(
        "AbdullahFageeh@gmail.com",
        f"{len(recent_entry) + len(recent_other)} Jobs Found (Last 7 Days)",
        body
    )
    
    # Also save to file
    digest_path = BASE_DIR / "logs" / f"digest_{today}.html"
    digest_path.write_text(body, encoding="utf-8")
    print(f"💾 Digest saved to {digest_path}")
    print(f"📊 Summary: {len(recent_entry)} entry-level + {len(recent_other)} other board jobs")

if __name__ == "__main__":
    generate_digest()
